name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          mingw-w64-x86_64-toolchain
          autoconf
          automake
          make
          libtool

    - name: Configure
      shell: msys2 {0}
      run: ./configure

    - name: Build
      shell: msys2 {0}
      run: make

    - name: Run checks
      shell: msys2 {0}
      run: make check

    - name: Run distcheck
      shell: msys2 {0}
      run: make distcheck
